pub mod gui;
use std::fs;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::Path;
use std::process::{Command, Stdio};
use std::thread;
use std::time::Duration;

#[cfg(unix)]
const DRIVER_BYTES: &[u8] = include_bytes!("driver/driver.ko");

pub fn start_scarecrow() {
    println!("=== Libre-Cyber-ScareCrow Initialization ===");
    println!("Creating fake analysis environment and sandbox artifacts...");

    #[cfg(unix)]
    {
        println!("Dropping Cyber-ScareCrow Linux Kernel Module (LKM) to disk...");
        let driver_path = "/tmp/scarecrow_lkm.ko";
        if let Err(e) = fs::write(driver_path, DRIVER_BYTES) {
            eprintln!("Failed to write LKM to disk: {}. Are you running as root?", e);
        } else {
            println!("  -> LKM dropped to: {}", driver_path);
            println!("Loading Cyber-ScareCrow Ring-0 Netfilter/Kprobes module...");
            let status = Command::new("insmod").arg(driver_path).status();
            if status.is_ok() && status.unwrap().success() {
                println!("  -> LKM loaded successfully! System sandboxed.");
            } else {
                eprintln!("  -> Failed to load LKM. Check dmesg for details.");
            }
        }
    }

    // 1. Create Dummy Artifacts
    let artifacts = vec![
        "/tmp/sandbox.log",
        "/tmp/cuckoo",
        "/tmp/VBoxGuestAdditions.iso",
    ];

    for artifact in artifacts {
        let path = Path::new(artifact);
        if artifact.ends_with('/') || !artifact.contains('.') {
            let _ = fs::create_dir_all(path);
        } else {
            let _ = fs::write(path, "Dummy artifact generated by Libre-Cyber-ScareCrow");
        }
        println!("  -> Spoofed artifact: {}", artifact);
    }

    // 2. Spawn Dummy Processes
    let processes = vec![
        "VBoxService",
        "vmtoolsd",
        "qemu-ga",
        "wireshark",
        "ida64",
        "strace",
        "gdb",
    ];

    println!("Spawning dummy process tree...");
    for proc_name in processes {
        let path = format!("/tmp/{}", proc_name);
        // Write a tiny shell script that just sleeps forever
        let script_content = "#!/bin/sh\nwhile true; do sleep 3600; done\n";
        if fs::write(&path, script_content).is_ok() {
            // Make executable
            #[cfg(unix)]
            {
                let mut perms = fs::metadata(&path).unwrap().permissions();
                perms.set_mode(0o755);
                let _ = fs::set_permissions(&path, perms);
            }

            // Spawn detached background process
            let _ = Command::new(&path)
                .stdin(Stdio::null())
                .stdout(Stdio::null())
                .stderr(Stdio::null())
                .spawn();

            println!("  -> Spawned dummy process: {}", proc_name);
        }
    }

    println!("Libre-Cyber-ScareCrow active. System now appears highly hostile to malware.");

    // Keep main thread alive if run as daemon
    loop {
        thread::sleep(Duration::from_secs(86400));
    }
}

