#!/usr/bin/env bash
#
# Arch Linux install — generated by the *nix Install Guides manual walkthrough.
#
# READ THIS BEFORE RUNNING IT. It repartitions /dev/nvme0n1 and does not
# ask twice. Nothing on that disk survives.
#
# The markdown guide explains why each command is here. This is the same
# sequence with the prose stripped out.

set -Eeuo pipefail

trap 'echo "FAILED at line $LINENO. The disk may be half-configured." >&2' ERR

# A generated script that runs without you having read it is exactly the
# failure mode this project exists to avoid.
read -rp "Have you read this script in full? Type YES to continue: " ok
[[ "$ok" == "YES" ]] || { echo "Stopping."; exit 1; }

lsblk
read -rp "Destroy everything on /dev/nvme0n1? Type the disk path to confirm: " confirm
[[ "$confirm" == "/dev/nvme0n1" ]] || { echo "Mismatch. Stopping."; exit 1; }

# ── block 1 ───────────────────────────────────────────────────────────
ls /sys/firmware/efi && echo UEFI   # confirms firmware mode

# Wireless, if you need it:
iwctl station wlan0 connect YOUR_SSID

ping -c3 archlinux.org
timedatectl set-ntp true

# ── block 2 ───────────────────────────────────────────────────────────
lsblk                       # identify the disk by size and model. Twice.

# ── block 3 ───────────────────────────────────────────────────────────
gdisk /dev/nvme0n1
#   o → new GPT (destroys the existing table)
#   n → 1 → +512M → type ef00   (EFI system partition)
#   n → 2 → rest        → type 8300   (Linux filesystem)
#   w → write

# ── block 4 ───────────────────────────────────────────────────────────
mkfs.fat -F32 /dev/nvme0n1p1
mkfs.ext4 /dev/nvme0n1p2
mount /dev/nvme0n1p2 /mnt
mkdir -p /mnt/boot
mount /dev/nvme0n1p1 /mnt/boot

# ── block 5 ───────────────────────────────────────────────────────────
pacstrap -K /mnt \
    base linux-firmware sudo vim man-db man-pages texinfo linux linux-headers linux-lts linux-lts-headers intel-ucode networkmanager efibootmgr zram-generator

genfstab -U /mnt >> /mnt/etc/fstab
cat /mnt/etc/fstab          # read it before you trust it
arch-chroot /mnt

# ── block 6 ───────────────────────────────────────────────────────────
ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
hwclock --systohc

sed -i 's/^#en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo "KEYMAP=us" > /etc/vconsole.conf

echo "archbox" > /etc/hostname
cat >> /etc/hosts <<'EOF'
127.0.0.1   localhost
::1         localhost
127.0.1.1   archbox.localdomain archbox
EOF

passwd                                     # root password
useradd -m -G wheel -s /bin/bash you
passwd you
EDITOR=vim visudo                          # uncomment %wheel ALL=(ALL:ALL) ALL

# ── block 7 ───────────────────────────────────────────────────────────
bootctl install

cat > /boot/loader/loader.conf <<'EOF'
default arch.conf
timeout 3
console-mode max
editor no
EOF

UUID=$(blkid -s UUID -o value /dev/nvme0n1p2)
cat > /boot/loader/entries/arch.conf <<EOF
title   Arch Linux
linux   /vmlinuz-linux
initrd  /intel-ucode.img
initrd  /initramfs-linux.img
options root=UUID=$UUID rw
EOF

# ── block 8 ───────────────────────────────────────────────────────────
systemctl enable NetworkManager

cat > /etc/systemd/zram-generator.conf <<'EOF'
[zram0]
zram-size = min(ram / 2, 8192)
compression-algorithm = zstd
EOF

# ── block 9 ───────────────────────────────────────────────────────────
exit
umount -R /mnt
reboot

# ── block 10 ──────────────────────────────────────────────────────────
sudo pacman -S --needed \
    hyprland waybar wofi xdg-desktop-portal-hyprland qt5-wayland qt6-wayland polkit-kde-agent pipewire pipewire-pulse pipewire-alsa wireplumber ttf-jetbrains-mono-nerd ufw git

# ── block 11 ──────────────────────────────────────────────────────────
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw enable
sudo systemctl enable ufw

# ── block 12 ──────────────────────────────────────────────────────────
git config --global user.name "Your Name"
git config --global user.email "you@example.com"
git config --global init.defaultBranch main

echo "Done. Read the markdown guide for what to do after the first boot."