[workspace]
members = [
    "anti-ducky",
    "libre-otp",
    "arch-iso-verifier", 
    "kernel-watcher", 
    "scarecrow", 
    "anti-evil-maid", 
    "arss-updater", 
    "arss-firewall"
]
resolver = "2"

[profile.release]
opt-level = 3       # Optimize for size
lto = true            # Enable Link-Time Optimization
codegen-units = 1     # Maximize size reduction optimizations
panic = "abort"       # Abort on panic (removes panic unwinding code)
strip = true          # Strip symbols from binary
