use eframe::egui;

pub struct AntiDuckyGui {
    log_messages: Vec<String>,
}

impl Default for AntiDuckyGui {
    fn default() -> Self {
        Self {
            log_messages: vec![
                "[anti-ducky] Connecting to root daemon via IPC...".to_string(),
                "[anti-ducky] Connected. Waiting for USB HID events...".to_string(),
            ],
        }
    }
}

impl eframe::App for AntiDuckyGui {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        // Tokyo Night Palette styling
        let mut style = (*ctx.style()).clone();
        style.visuals.window_fill = egui::Color32::from_rgb(26, 27, 38);
        style.visuals.panel_fill = egui::Color32::from_rgb(26, 27, 38);
        ctx.set_style(style);

        egui::CentralPanel::default().show(ctx, |ui| {
            ui.heading(
                egui::RichText::new("Anti-Ducky USB HID Monitor")
                    .color(egui::Color32::from_rgb(187, 154, 247))
                    .size(24.0),
            );
            ui.add_space(10.0);

            ui.horizontal(|ui| {
                if ui
                    .button(
                        egui::RichText::new("Approve Sandboxed Device")
                            .color(egui::Color32::from_rgb(158, 206, 106)),
                    )
                    .clicked()
                {
                    self.log_messages
                        .push("Sent APPROVE signal to IPC socket.".to_string());
                }
                if ui
                    .button(
                        egui::RichText::new("Reject/Quarantine Device")
                            .color(egui::Color32::from_rgb(247, 118, 142)),
                    )
                    .clicked()
                {
                    self.log_messages
                        .push("Sent REJECT signal to IPC socket.".to_string());
                }
            });

            ui.add_space(20.0);
            ui.label(
                egui::RichText::new("Daemon Logs:").color(egui::Color32::from_rgb(122, 162, 247)),
            );

            egui::ScrollArea::vertical().show(ui, |ui| {
                for msg in &self.log_messages {
                    ui.label(
                        egui::RichText::new(msg)
                            .color(egui::Color32::from_rgb(192, 202, 245))
                            .monospace(),
                    );
                }
            });
        });
    }
}

/// The window icon, as raw 64x64 RGBA.
///
/// Generated by `scripts/gen-icons.py` from the shared pixel grid, so the
/// title-bar icon, the favicon, the README banner and the site all come from
/// one source. Raw pixels rather than a PNG on purpose: decoding a PNG here
/// would mean linking an image decoder into a security tool to draw 64x64
/// pixels, which is dependency surface for nothing.
fn app_icon() -> egui::IconData {
    const RGBA: &[u8] = include_bytes!("../assets/icon-64.rgba");
    debug_assert_eq!(RGBA.len(), 64 * 64 * 4);
    egui::IconData { rgba: RGBA.to_vec(), width: 64, height: 64 }
}

pub fn start_gui() -> eframe::Result<()> {
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default()
            .with_inner_size([600.0, 400.0])
            .with_title("Anti-Ducky Dashboard")
            .with_icon(app_icon()),
        ..Default::default()
    };

    eframe::run_native(
        "Anti-Ducky",
        options,
        Box::new(|_cc| Box::<AntiDuckyGui>::default()),
    )
}
